name: API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run API tests with Newman
        run: >
          npx newman run "api-tests/E-Commerce API Tests.postman_collection.json"
          -e "api-tests/DummyJSON - QA.postman_environment.json"
          --env-var "base_url=https://dummyjson.com"
          --env-var "product_id=1"
          --env-var "user_id=1"
          --env-var "cart_id=1"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install Python dependencies
        run: pip install -r python-api-tests/requirements.txt

      - name: Install Playwright browser
        run: playwright install --with-deps chromium

      - name: Run Python API tests
        run: pytest python-api-tests=tests -v --html=reports/api-report.html --self-contained-html

      - name: Run Playwright UI tests
        run: pytest ui-tests/tests -v --html=repots/ui-report.html --self-contained-html

      - name: Upload Playwright failure screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-failure-screenshots
          path: ui-tests/screenshots/
          if-no-files-found: ignore

      - name: Upload API HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-test-report
          path: reports/api-report.html

      - name: Upload UI HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ui-test-report
          path: reports/ui-report.html