name: QA Automation Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  api-tests:
    name: API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Node dependencies
        run: npm ci

      - name: Run Postman API tests with Newman
        run: >
          npx newman run "api-tests/E-Commerce API Tests.postman_collection.json"
          -e "api-tests/DummyJSON - QA.postman_environment.json"
          --env-var "base_url=https://dummyjson.com"
          --env-var "product_id=1"
          --env-var "user_id=1"
          --env-var "cart_id=1"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install Python dependencies
        run: pip install -r python-api-tests/requirements.txt

      - name: Run Python API tests
        run: pytest python-api-tests/tests -v --html=reports/api-report.html --self-contained-html

      - name: Upload API HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-test-report
          path: reports/api-report.html


  ui-smoke-tests:
    name: UI Smoke Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install Python dependencies
        run: pip install -r python-api-tests/requirements.txt

      - name: Install Playwright browser
        run: playwright install --with-deps chromium

      - name: Run UI Smoke Tests
        run: pytest ui-tests/tests -m smoke -v --html=reports/ui-smoke-report.html --self-contained-html

      - name: Upload Playwright failure screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: smoke-failure-screenshots
          path: ui-tests/screenshots/
          if-no-files-found: ignore

      - name: Upload UI Smoke HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ui-smoke-report
          path: reports/ui-smoke-report.html


  ui-regression-tests:
    name: UI Regression Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install Python dependencies
        run: pip install -r python-api-tests/requirements.txt

      - name: Install Playwright browser
        run: playwright install --with-deps chromium

      - name: Run UI Regression Tests
        run: pytest ui-tests/tests -m regression -v --html=reports/ui-regression-report.html --self-contained-html

      - name: Upload Playwright failure screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: regression-failure-screenshots
          path: ui-tests/screenshots/
          if-no-files-found: ignore

      - name: Upload UI Regression HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ui-regression-report
          path: reports/ui-regression-report.html